# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/111OLurMrdGg8B3-4M-URNoYvjsFp_4ek
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

# Base URL with pagination
base_url = "https://pk.image1993.com/collections/ready-to-wear?page={}"

# Headers to mimic browser request
headers = {
    "User-Agent": "Mozilla/5.0"
}

# List to store scraped data
data = []

# Loop through pages
for page in range(1, 6):
    print(f"Scraping page {page}...")

    url = base_url.format(page)

    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()
    except requests.exceptions.RequestException as e:
        print(f"Error on page {page}: {e}")
        continue  # ✅ NOW correctly inside loop

    # Parse HTML
    soup = BeautifulSoup(response.text, "html.parser")

    # Find all links
    links = soup.find_all("a")

    # Extract product data
    for link in links:
        title = link.get_text(strip=True)
        href = link.get("href")

        if title and href:
            if "/products/" in href:
                if title.lower() not in ["pret", "gift packaging"]:
                    data.append({
                        "Title": title.strip(),
                        "Link": "https://pk.image1993.com" + href,
                        "Page": page
                    })

    # Respect website
    time.sleep(1)

# Use link as unique key
unique_data = {}

for item in data:
    unique_data[item["Link"]] = item

clean_data = list(unique_data.values())

df = pd.DataFrame(clean_data)
df.head()

df = df.drop_duplicates(subset="Link")
df = df.reset_index(drop=True)

df.head()

df.to_csv("data.csv", index=False)

print("Data saved successfully!")

import os
print(os.path.abspath("data.csv"))